#!/usr/bin/env bash
set -ex

# MODEL_NAMES=(
#    "cyto3" "nuclei" "cyto2_cp3" "cyto2" "cyto" "neurips_grayscale_cyto2"
# )

MODEL_NAMES=(
   "cyto2"
)

RETRAIN=true  # Set to true or false as needed

GPU_IDS=(0 1 2 3)

# Run 4 processes on different GPUs
for i in {0..3}; do
    model_name="${MODEL_NAMES[$i]}"
    gpu_id="${GPU_IDS[$i % 4]}"  # Correctly cycle through GPU IDs
    echo "Running $model_name on GPU $gpu_id"
    python -u run_cellpose_default.py "$model_name" "$RETRAIN" "$gpu_id" &
    if [ $((i % 4)) -eq 3 ]; then
        wait  # Wait for the current batch of 4 processes to finish
    fi
done

# Wait for all background processes to finish
wait