#!/usr/bin/env bash
set -ex

# MODEL_NAMES=(
#    "cyto3" "nuclei" "cyto2_cp3" "cyto2" "cyto" "neurips_grayscale_cyto2"
# )

MODEL_NAMES=(
   "cyto2"
)

RETRAIN=true  # Set to true or false as needed

GPU_COUNT=4  # Number of GPUs to allocate (set as an integer)

# Generate GPU IDs dynamically based on GPU_COUNT
GPU_IDS=($(seq 0 $((GPU_COUNT - 1))))

# Check if there is only one model in MODEL_NAMES
if [ ${#MODEL_NAMES[@]} -eq 1 ]; then
    model_name="${MODEL_NAMES[0]}"
    gpu_id="${GPU_IDS[0]}"  # Use the first GPU ID
    echo "Running $model_name on GPU $gpu_id"
    python -u run_cellpose_default.py "$model_name" "$RETRAIN" "$gpu_id"
else
    # Run multiple processes on different GPUs
    for i in $(seq 0 $((GPU_COUNT - 1))); do
        model_name="${MODEL_NAMES[$i]}"
        gpu_id="${GPU_IDS[$i % GPU_COUNT]}"  # Correctly cycle through GPU IDs
        echo "Running $model_name on GPU $gpu_id"
        python -u run_cellpose_default.py "$model_name" "$RETRAIN" "$gpu_id" &
        if [ $((i % GPU_COUNT)) -eq $((GPU_COUNT - 1)) ]; then
            wait  # Wait for the current batch of processes to finish
        fi
    done
fi



# Wait for all background processes to finish
wait